FROM python:3.8

ARG PINECONE_APIKEY

WORKDIR /app

ENV PINECONE_APIKEY=$PINECONE_APIKEY

COPY /app /app/app

WORKDIR /app/app

RUN pip install -r requirements.txt --no-cache-dir
RUN pip install git+https://github.com/openai/CLIP.git

EXPOSE 30000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "30000"]
